name: Build and push 'image' to Docker

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  workflow_dispatch: {}

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set Image Version
        run: echo "IMAGE_VERSION=$(echo ${{ github.ref }}#refs/heads/} | tr / -)" >> $GITHUB_ENV
      -
        name: Build Image
        uses: docker/build-push-action@v3
        with:
          context: docker
          load: true
          # TODO Make tag/version dependent on branch (push normal version only when on main branch, otherwise derive temporary version from branch name/datetime/commit-id/...)
          tags: jb090979/doctoolchain:${{ env.IMAGE_VERSION }}
      -
        name: Test Image
        run: |
          docker run \
            --rm \
            -v ${PWD}/test:/workspace \
            -w /workspace \
            jb090979/doctoolchain:${{ env.IMAGE_VERSION }} \
            bash -c "set -eu; test -w /etc/environment && ls -l /etc/environment; doctoolchain . tasks"
      -
        name: Push Image
        uses: docker/build-push-action@v3
        with:
          context: docker
          push:  ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: jb090979/doctoolchain:${{ env.IMAGE_VERSION }}
